In [1]:
using CSV, FileIO

In [2]:
data = load("../data/impvol_data.jld2")

Dict{String,Any} with 10 entries:
  "import_shares"             => [0.0 7.85e-7 … 0.000689 0.0004425; 7.42e-5 0.0…
  "pwt"                       => [0.824111 0.620073 … 0.747101 1.0]…
  "va"                        => [3271.5 1407.45 … 4209.16 41311.0]…
  "p_sectoral_data"           => [33.0109 64.7924 … 16.8926 36.7882]…
  "io_values"                 => [2.49202e5 2423.0 … 6491.5 0.0; 4183.8 56086.1…
  "total_output"              => [2.00728e6 8.11942e5 … 1.74308e6 66853.4]…
  "intermediate_input_shares" => [0.973154 0.0268455 … 0.528231 0.294862]…
  "trade_balance"             => [1184.95 -1239.14 … -406.84 1074.1]…
  "output_shares"             => [0.967079 0.032921 … 0.521898 0.318506]…
  "beta"                      => [0.230777 0.441 … 0.297884 0.370242]…

In [12]:
country_names = CSV.read("../experiments/baseline/output_table.csv")[:country_names]

25-element Array{Union{Missings.Missing, String},1}:
 "Australia"             
 "Austria"               
 "Belgium and Luxembourg"
 "Canada"                
 "China"                 
 "Colombia"              
 "Denmark"               
 "Finland"               
 "France"                
 "Germany"               
 "Greece"                
 "India"                 
 "Ireland"               
 "Italy"                 
 "Japan"                 
 "Mexico"                
 "Netherlands"           
 "Norway"                
 "Portugal"              
 "ROW"                   
 "South Korea"           
 "Spain"                 
 "Sweden"                
 "United Kingdom"        
 "United States"         

In [3]:
cpi = CSV.read("../data/cpi.csv")

36×26 DataFrames.DataFrame. Omitted printing of 21 columns
│ Row │ Time │ Australia [AUS] │ Austria [AUT] │ Belgium [BEL] │ Canada [CAN] │
├─────┼──────┼─────────────────┼───────────────┼───────────────┼──────────────┤
│ 1   │ 1972 │ 11.4464         │ 28.1734       │ 23.0586       │ 18.8251      │
│ 2   │ 1973 │ 12.487          │ 30.2951       │ 24.6624       │ 20.2347      │
│ 3   │ 1974 │ 14.4121         │ 33.1798       │ 27.7891       │ 22.4599      │
│ 4   │ 1975 │ 16.5973         │ 35.9819       │ 31.3373       │ 24.8569      │
│ 5   │ 1976 │ 18.8085         │ 38.6153       │ 34.1791       │ 26.7315      │
│ 6   │ 1977 │ 21.1238         │ 40.737        │ 36.6045       │ 28.8638      │
│ 7   │ 1978 │ 22.8148         │ 42.1931       │ 38.2409       │ 31.4539      │
│ 8   │ 1979 │ 24.8959         │ 43.7574       │ 39.9499       │ 34.3303      │
│ 9   │ 1980 │ 27.4194         │ 46.5265       │ 42.6061       │ 37.8077      │
│ 10  │ 1981 │ 30.0208         │ 49.6917       │ 45.8559       │ 42.5229      │
│ 11  │ 1982 │ 33.4287         │ 52.393        │ 49.8575       │ 47.1022      │
⋮
│ 25  │ 1996 │ 69.4069         │ 78.4941       │ 76.5368       │ 76.3523      │
│ 26  │ 1997 │ 69.563          │ 79.5192       │ 77.783        │ 77.5902      │
│ 27  │ 1998 │ 70.1613         │ 80.2528       │ 78.5213       │ 78.3629      │
│ 28  │ 1999 │ 71.2019         │ 80.7094       │ 79.4014       │ 79.7224      │
│ 29  │ 2000 │ 74.3757         │ 82.6019       │ 81.4218       │ 81.8904      │
│ 30  │ 2001 │ 77.6535         │ 84.7909       │ 83.4323       │ 83.9582      │
│ 31  │ 2002 │ 79.9688         │ 86.3259       │ 84.805        │ 85.8543      │
│ 32  │ 2003 │ 82.154          │ 87.4961       │ 86.1525       │ 88.2227      │
│ 33  │ 2004 │ 84.0791         │ 89.2995       │ 87.9593       │ 89.8612      │
│ 34  │ 2005 │ 86.3424         │ 91.3527       │ 90.4059       │ 91.8503      │
│ 35  │ 2006 │ 89.4121         │ 92.6696       │ 92.0252       │ 93.6892      │
│ 36  │ 2007 │ 91.4932         │ 94.6791       │ 93.7029       │ 95.6926      │

In [4]:
cpi[end:end,:]

1×26 DataFrames.DataFrame. Omitted printing of 21 columns
│ Row │ Time │ Australia [AUS] │ Austria [AUT] │ Belgium [BEL] │ Canada [CAN] │
├─────┼──────┼─────────────────┼───────────────┼───────────────┼──────────────┤
│ 1   │ 2007 │ 91.4932         │ 94.6791       │ 93.7029       │ 95.6926      │

In [5]:
# to conform with data structures
us_cpi = reshape(cpi[:,end] ./ cpi[1,end], (1,1,1,36))

1×1×1×36 Array{Float64,4}:
[:, :, 1, 1] =
 1.0

[:, :, 1, 2] =
 1.06178

[:, :, 1, 3] =
 1.17916

...

[:, :, 1, 34] =
 4.67019

[:, :, 1, 35] =
 4.82084

[:, :, 1, 36] =
 4.95837

In [6]:
dollar_price_index = data["pwt"] .* us_cpi

1×25×1×36 Array{Float64,4}:
[:, :, 1, 1] =
 0.824111  0.620073  0.816447  1.0138  …  0.469671  1.04781  0.747101  1.0

[:, :, 1, 2] =
 1.11992  0.781459  0.978674  1.09128  1.46411  …  1.23006  0.811203  1.06178

[:, :, 1, 3] =
 1.50229  0.917049  1.12899  1.26654  …  0.704648  1.3586  0.927185  1.17916

...

[:, :, 1, 34] =
 4.59907  4.81764  5.02688  4.45851  …  4.26361  5.6616  5.1814  4.67019

[:, :, 1, 35] =
 4.68595  4.95986  5.19679  4.86745  …  4.47361  5.84486  5.39862  4.82084

[:, :, 1, 36] =
 5.3599  5.52093  5.75983  5.23868  …  5.02791  6.49408  5.97413  4.95837

In [7]:
real_GDP_data = sum(data["va"], 3) ./ dollar_price_index

1×25×1×36 Array{Float64,4}:
[:, :, 1, 1] =
 64455.1  32858.7  40728.9  96150.9  …  37030.6  1.99307e5  1.12031e6

[:, :, 1, 2] =
 67128.2  32424.2  43883.7  1.04472e5  …  38390.3  2.09845e5  1.18077e6

[:, :, 1, 3] =
 63633.2  33232.6  44721.9  1.10412e5  …  40143.4  2.01172e5  1.15325e6

...

[:, :, 1, 34] =
 1.34195e5  57052.8  73653.4  2.36952e5  …  57251.3  3.9192e5  2.50782e6

[:, :, 1, 35] =
 1.41819e5  59326.7  75818.1  2.45268e5  …  59829.6  4.03127e5  2.57403e6

[:, :, 1, 36] =
 1.47524e5  61390.0  78980.8  2.5416e5  …  62356.9  4.19185e5  2.62123e6

In [8]:
include("../output.jl")
using ImpvolOutput
results = load("../experiments/baseline/actual/results.jld2")["results"]
parameters = load("../experiments/baseline/common_parameters.jld2")["parameters"]
real_GDP_model = sum(ImpvolOutput.make_series(results, :real_GDP), 3)

1×25×1×36 Array{Float64,4}:
[:, :, 1, 1] =
 63855.7  31864.1  38824.1  95853.6  …  37377.2  2.04764e5  1.13267e6

[:, :, 1, 2] =
 66268.0  31200.5  41837.8  1.04521e5  …  38398.4  2.13385e5  1.20157e6

[:, :, 1, 3] =
 63178.7  32255.5  41129.6  1.11434e5  …  40167.5  2.07574e5  1.18479e6

...

[:, :, 1, 34] =
 1.58892e5  69357.0  86544.0  268267.0  …  74405.3  4.81181e5  3.17756e6

[:, :, 1, 35] =
 1.7897e5  77431.3  90752.4  2.99321e5  …  83274.9  5.32559e5  3.46775e6

[:, :, 1, 36] =
 2.04374e5  88861.0  1.04261e5  3.6746e5  …  94962.5  6.19506e5  3.89584e6

In [9]:
data_volatility = ImpvolOutput.calculate_volatilities(real_GDP_data, parameters, true)[:].^0.5
model_volatility = ImpvolOutput.calculate_volatilities(real_GDP_model, parameters, true)[:].^0.5
[data_volatility model_volatility]

25×2 Array{Float64,2}:
 0.0305473  0.0320749
 0.0107807  0.0207841
 0.0167103  0.0313297
 0.0145287  0.0241037
 0.0754594  0.0800216
 0.0283547  0.034207 
 0.0152353  0.0249971
 0.0224505  0.02697  
 0.0126346  0.0174015
 0.0129384  0.0185548
 0.0156778  0.0181153
 0.0310229  0.0332864
 0.0254603  0.0337322
 0.0102044  0.0166638
 0.0148759  0.0189343
 0.0250657  0.032459 
 0.01077    0.0211015
 0.0244207  0.0313195
 0.0327996  0.0392414
 0.0392363  0.0420262
 0.0325697  0.0299515
 0.0130455  0.0177523
 0.0150565  0.0202304
 0.014959   0.0171067
 0.0162804  0.0187463

In [18]:
function regression(x, y)
    X = [ones(length(x)) x]
    beta = X \ y
    R2 = var(X * beta) / var(y)
    return (beta, R2)
end

regression (generic function with 1 method)

In [19]:
beta, R2 = regression(data_volatility, model_volatility)
correlation = R2^.5


0.9655989762148681

In [20]:
using Plots
fm = x->repr(round(x, 3))
label = "y = $(fm(beta[1]))+$(fm(beta[2]))x\nR2 = $(fm(R2))"
plot(data_volatility, X*beta, label=label, xlabel="Data volatility (standard deviation)", size=(800,500))
scatter!(data_volatility, model_volatility, label="", ylabel="Model volatility (standard deviation)")
x = 0.002
for i=1:length(data_volatility)
    annotate!(data_volatility[i], model_volatility[i]+x, text(country_names[i], :black, :center, 10))
end
savefig("../Figure2.pdf")

In [21]:
# without china
beta, R2 = regression([data_volatility[1:4]; data_volatility[6:end]], [model_volatility[1:4]; model_volatility[6:end]])
correlation = R2^.5

0.9021922265297351

In [23]:
# correlation of variances
beta, R2 = regression(data_volatility.^2, model_volatility.^2)
correlation = R2^.5

0.9886188789008895

In [24]:
# correlation of variances
# without china
beta, R2 = regression([data_volatility[1:4]; data_volatility[6:end]].^2, [model_volatility[1:4]; model_volatility[6:end]].^2)
correlation = R2^.5

0.9056866572357395